---

- name: restart service (openrc)
  listen: restart service
  service:
    name: "{{ thanos_service_name }}"
    state: restarted
  when:
    - ansible_service_mgr | lower == 'openrc'

- name: restart service (systemd)
  listen: restart service
  service:
    name: "{{ thanos_service_name }}"
    state: restarted
  when:
    - ansible_service_mgr | lower == 'systemd'
    - thanos_service_state == 'started'
    - thanos_service_enabled

- name: reload service (systemd)
  listen: reload service
  service:
    name: "{{ thanos_service_name }}"
    state: reloaded
  when:
    - ansible_service_mgr | lower == 'systemd'
    - thanos_service_state == 'started'
    - thanos_service_enabled

- name: service handler
  listen: service handler
  service:
    name: "{{ thanos_service_name }}"
    state: "{{ thanos_service_state }}"
    enabled: "{{ thanos_service_enabled }}"


- name: daemon-reload
  become: true
  systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

...
